# Generated by Django 4.2.3 on 2023-07-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('bloque', 'Bloqué'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=50)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('operateur', models.CharField(max_length=50)),
                ('machine', models.CharField(default=None, max_length=50)),
                ('is_case', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('bloque', 'Bloqué'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=50)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comm_tf.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('case', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('bloque', 'Bloqué'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=50)),
                ('crée_par', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tâche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comm_tf.tache')),
            ],
        ),
    ]
