# Generated by Django 4.2.3 on 2023-07-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm_tf', '0002_remove_operation_case_remove_tache_is_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='operateur',
        ),
    ]
