# Generated by Django 4.2.3 on 2023-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_societe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='users',
        ),
        migrations.AddField(
            model_name='societe',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
