# Generated by Django 4.2.3 on 2023-07-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_societe_adresse_remove_societe_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='password',
        ),
        migrations.AddField(
            model_name='societe',
            name='code',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
