# Generated by Django 4.2.3 on 2023-07-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_societe_password_societe_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='societe',
            old_name='code',
            new_name='Password_societe',
        ),
    ]
